FROM flyway/flyway:6.3

COPY migrations/ /flyway/sql
COPY scripts/db_clean_entrypoint .

ENV FLYWAY_CONNECT_RETRIES=10
ENV FLYWAY_IGNORE_INVALID_MIGRATION_NAMES="false"
ENV FLYWAY_CLEAN_DISABLED="false"

ENTRYPOINT ["sh", "db_clean_entrypoint"]
